version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-c
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - database
      - redis
    volumes:
      - ./src:/main
    env_file:
      - .env
    networks:
      - dbnetwork

  database:
    image: postgres:15
    container_name: monitoring-url
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: redis-c
    ports:
      - "6379:6379"
    networks:
      - dbnetwork

networks:
  dbnetwork:
    driver: bridge

volumes:
  postgres:
    name: nest-db
